[workspace]
authors = ["Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>"]
channels = ["conda-forge"]
name = "django-guardian-mwe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
[tasks.remove-db]
cmd = "rm mwe/db.sqlite3"

[tasks.run-migration]
cmd = "cd mwe && python manage.py migrate"

[tasks.flush-db]
cmd = "cd mwe && python manage.py flush --noinput"

[tasks.test]
depends-on = [
  { task = "flush-db" },
  { task = "run-migration" },
]
cmd = "cd mwe && python manage.py shell < ../test.py"

[dependencies]
python = ">=3.14.3,<3.15"
django = ">=6.0.3,<7"
django-guardian = ">=3.0.0,<4"
