[workspace]
authors = ["Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>"]
channels = ["conda-forge"]
name = "django-guardian-mwe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
django = ">=6.0.3,<7"
django-guardian = ">=3.0.0,<4"
