# Generated by Django 6.0.3 on 2026-03-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
            options={
                "permissions": (("answer", "Answer"),),
            },
        ),
        migrations.CreateModel(
            name="QuestionWithDuration",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.question",
                    ),
                ),
                ("answer", models.DurationField()),
            ],
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionWithText",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.question",
                    ),
                ),
                ("answer", models.TextField()),
            ],
            bases=("polls.question",),
        ),
    ]
