# Generated by Django 6.0.3 on 2026-03-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionwithduration",
            options={"permissions": (("answer", "Answer"),)},
        ),
        migrations.AlterModelOptions(
            name="questionwithtext",
            options={"permissions": (("answer", "Answer"),)},
        ),
    ]
